version: '3'
services:
  nvidia-sample:
    image: nvidia:cuda
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     #please change path, if your directory is different.
    environment:
      DISPLAY: $DISPLAY
    working_dir: /workspace
    network_mode: host

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: nvidia-smi -l 1
